name: Docker Publish

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and Push Docker Image
        run: |
          docker pull registry.hf.space/camenduru-mochi-1-preview-temp:latest
          docker tag registry.hf.space/camenduru-mochi-1-preview-temp:latest camenduru/mochi-1-preview-temp:latest
          docker push camenduru/mochi-1-preview-temp:latest
